// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace nashpati.skin
{
	public partial class AddNewController : NSViewController, IPreferencesListener
	{
		private Preferences prefs;

		public AddNewController (IntPtr handle) : base (handle)
		{
		}

		public void PreferencesChanged(Preferences preferences)
		{
			prefs = preferences;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
		}

		partial void AddClicked(NSObject sender)
		{
			var url = UrlInput.StringValue;
			Console.WriteLine("URL: " + url);
			if (Uri.IsWellFormedUriString(url, UriKind.Absolute) && Sources.IsUrlSupported(url))
			{
				// TODO: Add better URL validation;
				NSNotificationCenter.DefaultCenter.PostNotificationName(new NSString("NewUrlAdded"), new NSString(url));
				this.DismissController(this);
			}
		}

		partial void UrlInputAction(NSObject sender)
		{
			AddClicked(sender);
		}
	}
}
