// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace nashpati.skin
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{

		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();

			// Main window config.
			Window.TitleVisibility = NSWindowTitleVisibility.Hidden;
			Window.TitlebarAppearsTransparent = true;
			Window.MovableByWindowBackground = true;
		}
	}
}
