// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace nashpati.skin
{
	public partial class NowPlayingController : NSViewController
	{
		private NSMutableArray _playlist;

		[Export("playlistItemArray")]
		public NSArray Playlist
		{
			get
			{
				return _playlist;
			}
		}

		public NowPlayingController (IntPtr handle) : base (handle)
		{
			_playlist = new NSMutableArray();
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// TODO: Debug data, remove on release.
			DummyDataUtils.playlistItems().ForEach(AddPerson);
		}

		[Export("addObject:")]
		public void AddPerson(PlaylistItem person)
		{
			WillChangeValue("playlistItemArray");
			_playlist.Add(person);
			DidChangeValue("playlistItemArray");
		}

		[Export("insertObject:inPlaylistItemArrayAtIndex:")]
		public void InsertPerson(PlaylistItem person, nint index)
		{
			WillChangeValue("playlistItemArray");
			_playlist.Insert(person, index);
			DidChangeValue("playlistItemArray");
		}

		[Export("removeObjectFromPlaylistItemArrayAtIndex:")]
		public void RemovePerson(nint index)
		{
			WillChangeValue("playlistItemArray");
			_playlist.RemoveObject(index);
			DidChangeValue("playlistItemArray");
		}

		[Export("setPlaylistItemArray:")]
		public void SetPeople(NSMutableArray array)
		{
			WillChangeValue("playlistItemArray");
			_playlist = array;
			DidChangeValue("playlistItemArray");
		}

	}
}
