// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AVFoundation;

namespace nashpati.skin
{
	public partial class PlayerViewController : NSViewController
	{
		AVPlayer player;
		//AVPlayerLayer playerLayer;
		AVAsset asset;
		AVPlayerItem playerItem;

		public PlayerViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			asset = AVAsset.FromUrl(NSUrl.FromFilename(Environment.GetEnvironmentVariable("NASHPATI_SAMPLE_VIDEO_FILE") ?? "/temp/sample.mp4"));
			playerItem = new AVPlayerItem(asset);
			player = new AVPlayer(playerItem);
			PlayerView.Player = player;
			PlayerView.Player.Play();

		}
	}
}
