// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace nashpati.skin
{
	public partial class PlayerPanelController : NSWindowController
	{
		public PlayerPanelController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad()
		{
			base.WindowDidLoad();
			((NSButton)this.Window.ContentView.ViewWithTag(10)).Activated += (sender, e) =>
				MainWindowController.MainWindow.AddChildWindow(this.Window, NSWindowOrderingMode.Above);
			((NSButton)this.Window.ContentView.ViewWithTag(100)).Activated += (sender, e) =>
				MainWindowController.MainWindow.RemoveChildWindow(this.Window);


			((NSPanel)Window).FloatingPanel = true;
			Window.MovableByWindowBackground = true;
			Window.Level = NSWindowLevel.Floating;
			Window.CollectionBehavior = NSWindowCollectionBehavior.MoveToActiveSpace | NSWindowCollectionBehavior.FullScreenAuxiliary;
		}
	}
}
